stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages


  prepare_base_model:
    cmd: python src/deepClassifier/pipeline/st_02_prepare_base_model.py
    deps:
      - src/deepClassifier/pipeline/st_02_prepare_base_model.py
      - configs/config.yaml
    params:
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - IMAGE_SIZE
      - LEARNING_RATE

    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/deepClassifier/pipeline/st_03_training.py
    deps:
      - src/deepClassifier/pipeline/st_03_training.py
      - src/deepClassifier/components/prepare_callbacks.py
      - configs/config.yaml
      - artifacts/prepare_base_model
      - artifacts/data_ingestion/PetImages
    params:
      - BATCH_SIZE
      - EPOCHS
      - AUGMENTATION
      - IMAGE_SIZE
    outs:
      - artifacts/training/model.h5